### ISSUE TITLE
minimum version of nasm required

### ISSUE THREAD

**Issue by notwa** [Shizmob/smol#12]
old versions of nasm (pre-2.13) fail to assemble [header64.asm](https://github.com/Shizmob/smol/blob/5dd269d/rt/header64.asm) with:
```
header64.asm:43: error: operand 1: expression is not simple or relocatable
header64.asm:55: error: operand 1: expression is not simple or relocatable
```
so this might be worth mentioning in the README.

**Comment by PoroCYon** [comment]
Done that, sorry for not noticing this issue earlier.
